image: openjdk:8-jdk

stages:
  - build

.quality-check:
  stage: build
  tags:
    - oc
    - voyager
  script:
    - code_check
  when: manual  


variables:
  MAVEN_CLI_OPTS: "-s .mvn/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.mvn/repository"

test:
  stage: build
  script:
    - run_test
  tags:
    - oc
    - voyager


#--------------------------------------------------------------------------

.ci_functions: &ci_functions |
  set +x

  run_test(){
    mvn install $MAVEN_CLI_OPTS
  }

    code_check(){
    mvn sonar:sonar $MAVEN_CLI_OPTS
  }



before_script:
  - *ci_functions