image: repo.djdev.org/docker-public/buildbox:jdk8

variables:
  MAVEN_CLI_OPTS: "-s .mvn/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.mvn/repository"

stages:
  - build

.quality-check:
  stage: build
  tags:
    - voyager
  script:
    - code_check
  when: manual  

test:
  stage: build
  tags:
    - voyager
  script:
    - run_test
  artifacts:
    when: always
    #paths:
    # - zipped_report/*
    #reports:
    #  junit: zipped_report/*.zip

      
#--------------------------------------------------------------------------

.ci_functions: &ci_functions |
  set +x

  run_test(){
    mvn install $MAVEN_CLI_OPTS
  }

  code_check(){
    mvn sonar:sonar $MAVEN_CLI_OPTS
  }



before_script:
  - *ci_functions