image: registry.og-cs.hr/cm-infa/docker-base-images/openjdk:latest

#--------------------------------------------------------------------------

.ci_functions: &ci_functions |
  set +x

  mvn_build() {
    chmod +x mvnw
    ./mvnw $MAVEN_CLI_OPTS deploy
  }

before_script:
  - *ci_functions